[profile.default]
src = "solidity-sdk/src"
out = "solidity-sdk/out"
libs = ["solidity-sdk/lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
solc = "0.8.34"
evm_version = "prague"
bytecode_hash = "none"
cbor_metadata = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fmt]
exclude = ["solidity-sdk/lib/**"]
