[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.34"
evm_version = "prague"
bytecode_hash = "none"
cbor_metadata = false
remappings = ["pod-sdk/=../../../solidity-sdk/src/"]
allow_paths = ["../../../solidity-sdk"]

[fmt]
exclude = ["lib/**"]
