[package]
name = "pod-optimistic-auction"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "1.0.9", features = ["sol-types", "contract"] }
serde = { version = "1.0", features = ["derive"] }