[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "prague"
bytecode_hash = "none"
cbor_metadata = false
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "pod-sdk/=../solidity-sdk/src/",
    "pod-protocol/=./src/",
]
allow_paths = ["../solidity-sdk"]
via_ir = true
optimizer = true
optimizer_runs = 4294967295 

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
exclude = ["lib/**"]

[lint]
exclude_lints = ["incorrect-shift"]
