[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "prague"
bytecode_hash = "none"
cbor_metadata = false
remappings = [
    "pod-sdk/=../../solidity-sdk/src/",
]
allow_paths = ["../../solidity-sdk"]

[fmt]
exclude = ["lib/**"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
