[package]
name = "pod-examples-solidity"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "0.12.1", features = ["sol-types", "contract"] }
serde = { version = "1.0.214", features = ["derive"] }